# fly.toml app configuration file generated for axe-lang-misty-wildflower-3244 on 2024-12-27T22:46:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'axe-lang-misty-wildflower-3244'
primary_region = 'sjc'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  dockerfile = "./api/Dockerfile"
